# set mod key to windows key
set $mod Mod4

# set a few variable names
set $browser firefox
set $term foot
set $menu fuzzel
set $mail thunderbird
set $file_manager thunar

# Start a terminal
bindsym $mod+Return exec $term 
# Start a terminal and start neovim
bindsym $mod+N exec $term -- bash -c nvim

# Kill focused window
bindsym $mod+q kill

# Start launcher (dmenu, wofi, fuzzle...)
bindsym $mod+d exec $menu -i
# menu launcher + cliphist
bindsym $mod+u exec cliphist list | $menu -d | cliphist decode | wl-copy
# Drag floating windows by holding down $mod and left mouse button.
floating_modifier $mod normal

# Reload the configuration file
bindsym $mod+Shift+r reload

# wlogout, a power menu
# bindsym $mod+Shift+p exec wlogout

# used instead of a power menu
bindsym $mod+Shift+p mode "logout"
mode logout {
    bindsym Escape mode default
    bindsym r exec systemctl reboot; mode default
    bindsym p exec systemctl poweroff; mode default
    bindsym s exec systemctl suspend; mode default
    bindsym l exec swaylock --image $HOME/pictures/wallpapers/lockscreen/*; mode default
    bindsym o exec sway exit
}

# Bluetooth menu
bindsym $mod+Shift+b exec DMENU_BLUETOOTH_LAUNCHER=fuzzel dmenu-bluetooth
# Wifi menu
bindsym $mod+Shift+w exec networkmanager_dmenu
# Pulseaudio
bindsym $mod+p exec pavucontrol

# take a screenshot - note that the screenshot path is automatically input into the clipboard
# full screen 
bindsym $mod+Shift+s exec bash $HOME/.config/sway/scripts/screenshot_full.sh
# selection
bindsym $mod+s exec bash $HOME/.config/sway/scripts/screenshot_select.sh

# open file manager quickly
bindsym $mod+e exec $file_manager

# Moving around:
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# Move the focused window with the same, but add Shift
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# Modify the split direction
bindsym $mod+b splith 
bindsym $mod+v splitv

# Make the current focus fullscreen
bindsym $mod+f fullscreen
# Toggle the current focus between tiling and floating mode
bindsym $mod+Shift+space floating toggle
# Swap focus between the tiling area and the floating area
bindsym $mod+space focus mode_toggle
# Move the currently focused window to the scratchpad
bindsym $mod+Shift+minus move scratchpad
# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
bindsym $mod+minus scratchpad show

# size windows
bindsym $mod+Left resize shrink width 10 px or 5 ppt
bindsym $mod+Down resize grow height 10 px or 5 ppt
bindsym $mod+Up resize shrink height 10 px or 5 ppt
bindsym $mod+Right resize grow width 10 px or 5 ppt

# audio control
# bindsym xf86audioraisevolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ 
# bindsym xf86audiolowervolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
# bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym xf86audioraisevolume exec $HOME/.config/sway/scripts/changevolume.sh up
bindsym xf86audiolowervolume exec $HOME/.config/sway/scripts/changevolume.sh down
bindsym XF86AudioMute exec $HOME/.config/sway/scripts/changevolume.sh mute

# Brightness control
# bindsym XF86MonBrightnessDown exec brightnessctl set 10%- 
# bindsym XF86MonBrightnessUp exec brightnessctl set 10%+
bindsym XF86MonBrightnessUp exec $HOME/.config/sway/scripts/changebrightness.sh up
bindsym XF86MonBrightnessDown exec $HOME/.config/sway/scripts/changebrightness.sh down
