# Status Bar:
# Read `man 5 sway-bar` for more information about this section.
# bar {
# 
#     font JetBrainsMono NL 12
#     position bottom
#     gaps 0 0
#     height 45
# 
#     # When the status_command prints a new line to stdout, swaybar updates.
#     # The default just shows the current date and time.
#     # status_command while date +'%d-%m-%Y  /  %H:%M  '; do sleep 10; done
#     status_command SCRIPT_DIR=~/.config/i3blocks/scripts i3blocks
# 
#     colors {
#         statusline #FFFFFF
#         background #303446
#         focused_workspace #51576d #51576d #FFFFFF
#         inactive_workspace #303446 #303446 #737994
#         urgent_workspace #51576d #51576d #c6d0f5
#     }
# 
# }
