# determine font
font "JetBrainsMono NL" 10
# set background
output * bg /home/benjamin/pictures/wallpapers/permanent/* fill

# colors of the frame, depending on focused/unfocused mode
client.focused #626880 #d08770 #FFFFFF #ebcb8b
client.focused_inactive #303446 #303446 #626880 #303446
client.unfocused #000000 #000000 #000000
exec_always inactive-windows-transparency.py --opacity 0.8

# gaps between windows
gaps inner 10px

# title bar 
default_border none
default_floating_border none
# text algign for the title bar -- might be inactive
# title_align center

# swayfx ricing -- swayfx needed
# blur enable
# blur_passes 3
# blur_radius 2
# blur_noise 0.0
# blur_brightness 1.0
# blur_contrast 1.0
# blur_saturation 1.0
#
corner_radius 10
# shadows disable
# shadow_blur_radius 5
# shadow_color #000000FF
# shadow_offset 5 5
#
# default_dim_inactive 0.0
